from pathlib import Path

# anchor paths to this file so scripts work from any directory
_HERE    = Path(__file__).parent   # model1_cnn/
_PROJECT = _HERE.parent            # ML class project/

# data lives at the project root, shared across all 4 models
DATA_ROOT = _PROJECT / "data"

METADATA_CSV  = DATA_ROOT / "all_labels.csv"
IMAGE_DIR     = DATA_ROOT / "classification_data"

# these two files are generated by data_exploration.py
FILTERED_METADATA_CSV = DATA_ROOT / "filtered_metadata.csv"
CLASS_MAP_JSON        = DATA_ROOT / "class_map.json"

CHECKPOINT_DIR        = _HERE / "checkpoints"
BEST_MODEL_PATH       = CHECKPOINT_DIR / "best_model.pth"

OUTPUT_DIR            = _HERE / "outputs"
CONFUSION_MATRIX_PATH = OUTPUT_DIR / "confusion_matrix.png"
GRADCAM_DIR           = OUTPUT_DIR / "gradcam"

# column names in all_labels.csv
COL_IMAGE_PATH = "image_path"
COL_LABEL      = "label_code_id"   # grouping by manufacturer -- see data_exploration.py

# columns we check for nulls before filtering
REQUIRED_COLS_NULLCHECK = ["image_path", "label", "is_ref", "is_front"]

# we only use the cleanly segmented images, not the fcn_mix_weight ones
SUBFOLDER_FILTER = "segmented_nih_pills_224"

# change this to use more classes -- re-run data_exploration.py after changing
NUM_CLASSES = 10

# train/val/test split ratios
TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15
TEST_RATIO  = 0.15
RANDOM_SEED = 42

# image settings
IMAGE_SIZE    = 224
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# training hyperparameters
BATCH_SIZE    = 32
NUM_EPOCHS    = 20
LEARNING_RATE = 1e-3
DROPOUT_RATE  = 0.5

# augmentation settings (training only)
ROTATION_DEGREES        = 15
COLOR_JITTER_BRIGHTNESS = 0.3
COLOR_JITTER_CONTRAST   = 0.3

# grad-cam
NUM_GRADCAM_SAMPLES = 5
